pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                script {
                    git branch: 'master',
                        url: 'https://github.com/mklmfane/sre-technical-tests.git'
                }
            }
        }
    
        stage('Authenticate to AWS') {
            steps {
                script {
                    echo 'Authenticating to AWS...'

                    // Use Jenkins credentials for AWS authentication
                    withCredentials([
                        aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', 
                            secretKeyVariable: 'AWS_SECRET_ACCESS_KEY', 
                            credentialsId: 'AWS_ACCESS') // Replace with your Jenkins credential ID
                    ]) {
                        sh '''
                          export AWS_DEFAULT_REGION="eu-west-1"
                        '''
                    }
                }
            }
        }

        stage('Terraform Init') {
            steps {
                script {
                    // Requires to install terraform plugin in jenkins
                    echo 'Initializing Terraform...'
                    
                    def currentDir = pwd()
                        dir("${currentDir}/exercise2") {
                            sh '''
                                ls
                                terraform init    
                        '''
                    }
                    
                }
            }
        }
        
        stage('Terraform plan') {
            steps {
                script {
                    // Requires to install terraform plugin in jenkins
                    echo 'Initializing Terraform...'
                    
                    def currentDir = pwd()
                        dir("${currentDir}/exercise2") {
                            sh '''
                                ls
                                terraform plan -var-file="terraform_vars.tfvars" -no-color -out=tfplan                                    
                            '''
                    }
                    
                }
            }
        }

    }


    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed. Check the logs for details.'
        }
    }
}
